import type { Page } from '../hr/dashboard-contracts';
export type Finding = { code: string; message: string; sourceIds: string[] };
export type Interval = { startUtc: string; endUtc: string };
export type Event = {
  attendanceEventId: string;
  employeeId: string;
  occurredAtUtc: string;
  businessDate: string;
  businessTimeZone: string;
  direction: string;
  source: string;
  reason: string | null;
  receivedAtUtc: string;
  actorId: string | null;
  originalSourceTimestamp: string | null;
  employeeWasInactive: boolean;
  employmentReadiness: string;
  intakeAnomalies: string[];
};
export type Coverage = {
  readiness: string;
  coveragePartitionAvailable: boolean;
  potentialAbsence: boolean;
  scheduledIntervals: Interval[];
  observedPresenceMilliseconds: number;
  scheduledMilliseconds: number | null;
  presenceCoveredScheduledMilliseconds: number | null;
  approvedLeaveCoveredScheduledMilliseconds: number | null;
  paidLeaveCoveredMilliseconds: number | null;
  unpaidLeaveCoveredMilliseconds: number | null;
  unexplainedScheduledMilliseconds: number | null;
  coverageTruncationResidualMilliseconds: number | null;
  rawStartVarianceTicks: number | null;
  rawStartVarianceMilliseconds: number | null;
  calculationContractVersion: string;
};
export type ReportFacts = Coverage & {
  events: Pick<Event, 'attendanceEventId' | 'occurredAtUtc' | 'direction' | 'source'>[];
  approvedLeaves: {
    leaveId: string;
    isPaid: boolean;
    chargedIntervals: { startTime: string; endTime: string }[];
  }[];
  isConfirmedAbsent: boolean;
  isLate: boolean | null;
  leaveState: string;
  leaveExtent: string;
};
export type Row = {
  employeeId: string;
  employeeNumber: string;
  displayName: string;
  departmentName: string | null;
  designationName: string | null;
  businessDate: string;
  workState: string;
  timingState: string;
  recordState: string;
  requiresReview: boolean;
  readyToFinalize: boolean;
  latestHistoricalRevision: number | null;
  finalizedAtUtc: string | null;
  isStale: boolean;
  requiresReopen: boolean;
  isReopened: boolean;
  isCurrentlyValidated: boolean;
  findings: Finding[];
  changedSources: Finding[];
  attentionCategories: string[];
  live: ReportFacts;
  official: ReportFacts | null;
};
export type Counts = {
  effectiveEmployees: number;
  employeeDates: number;
  scheduled: number;
  notScheduled: number;
  onTime: number;
  late: number;
  approvedLeave: number;
  confirmedAbsence: number;
  potentialAbsence: number;
  requiresReview: number;
  finalized: number;
  stale: number;
  configurationRequired: number;
  reopened: number;
  unfinalizedPastDays: number;
  readyToFinalize: number;
};
export type Overview = {
  businessDate?: string;
  from?: string;
  to?: string;
  businessTimeZone: string;
  generatedAtUtc: string;
  counts: Counts;
  rows: Page<Row>;
};
export type Day = Coverage & {
  employeeId: string;
  businessDate: string;
  businessTimeZone: string;
  expectedWork: {
    readiness: string;
    finding: string | null;
    calendarName: string | null;
    scheduleKind: string | null;
  };
  events: Event[];
  findings: Finding[];
  isLateUnderCurrentPolicy: boolean | null;
  currentGracePolicy: string;
  clockInGraceMinutes: number;
  approvedLeaves: {
    leaveId: string;
    observedStatus: string;
    isPaid: boolean;
    snapshotVersion: number;
  }[];
  presenceCoveredScheduledIntervals: Interval[];
  approvedLeaveCoveredIntervals: Interval[];
  unexplainedScheduledIntervals: Interval[];
  presenceLeaveOverlapIntervals: Interval[];
};
export type ReviewAction = {
  id: string;
  sequence: number;
  action: string;
  attendanceEventId: string | null;
  reason: string;
  occurredAtUtc: string;
  actorUserId: string | null;
  origin: string;
};
export type Revision = {
  id: string;
  revision: number;
  finalizedAtUtc: string;
  actorUserId: string | null;
  snapshot: {
    calculation: Day;
    rawEvents: Event[];
    reviewHistory: ReviewAction[];
    isConfirmedAbsent: boolean;
  };
};
export type Review = {
  employeeId: string;
  businessDate: string;
  version: number;
  sourceFingerprint: string;
  rawCalculation: Day;
  calculation: Day;
  reviewCase: { state: string; originalCalculation: Day } | null;
  history: ReviewAction[];
  latestHistoricalFinalizedRevision: Revision | null;
  isStale: boolean;
  requiresReopen: boolean;
  isReopened: boolean;
  isCurrentlyValidated: boolean;
  isConfirmedAbsent: boolean;
  changedSources: Finding[];
};
export type History = {
  employeeId: string;
  from: string;
  to: string;
  businessTimeZone: string;
  dates: Row[];
};
export type Summary = {
  isComplete: boolean;
  effectiveEmploymentDates: number;
  finalizedWorkingDays: number;
  unfinalizedWorkingDays: number;
  staleFinalizedDays: number;
  reopenedDays: number;
  configurationRequiredDays: number;
  requiresReviewDays: number;
  scheduledMilliseconds: number;
  presenceCoveredScheduledMilliseconds: number;
  approvedLeaveCoveredScheduledMilliseconds: number;
  unexplainedScheduledMilliseconds: number;
  coverageTruncationResidualMilliseconds: number;
};
export type Legacy = {
  attendanceId: string;
  attendanceDate: string;
  attendanceStatusName: string;
  checkIn: string | null;
  checkOut: string | null;
  remarks: string | null;
};
